FROM node:10-alpine as node

#RUN mkdir -p /var/app/node_modules && chown -R node:node /var/app
RUN mkdir -p /var/app

WORKDIR /var/app

COPY package*.json /var/app/

#development
ENV BUILD_ENV development

# staging
#ENV BUILD_ENV staging

#Production
#ENV BUILD_ENV production

RUN npm config set registry http://registry.npmjs.org

#USER node

#RUN npm install
RUN apk --no-cache --virtual build-dependencies add \
    python \
    make \
    g++ \
    && npm cache clean --force \	
    && npm install \
    && npm install -g nodemon \
    && apk del build-dependencies

COPY . /var/app/

EXPOSE 8080

#development
CMD [ "npm", "run", "start"]

#staging
#CMD [ "npm", "run", "build-staging"]

#production
#CMD [ "npm", "run", "build-production"]

