// const themeColor = "themeColor"; // #f1b231 TODO change it after web designs get final
const themeColor = "orange";
const themeBgColor = "#666";

const LOGIN = {
  portal: "Franchise",
  login: "Login",
  username: "Username",
  password: "Password",
  invalid: "Invalid Input",
  journeyType: "login",
};

const FORGOT_PASSWORD = {
  email: "Email",
  link: "Send Link",
  emptyField: "Enter Registered Email",
  forgot_password: "Forgot Password ?",
  registeredEmail: "Registered email",
  journeyType: "forgot password",
};

const RESET_PASSWORD = {
  title: "Reset Password",
  password: "Password",
  confirmPassword: "Confirm password",
  resetPaswordBtn: "Reset Password",
};

const OTP = {
  title: "OTP Verification",
  labelText: "OTP verification",
  resend: "Resend",
  otpVerify: "Verify OTP",
};

const DASHBOARD = {
  TOP_5_CDM: "Chief Development Manager (CDM)",
  TOP_5_AM: "Area Manager (AM)",
  TOP_5_BM: "Business Manager (BM)",
  AGM: "AGM",
  AM: "AM",
  BM: "BM",
  CDM: "CDM",
  MONEY_STATS: "Money Stats",
  AGM_SUBTITLE: "Total revenue generated by each AGM",
  MONEY_SUBTITLE: "Money stats of all the sectors",
  AGM_FULL: "Additional General Manager",
  AM_FULL: "Area Manager",
  BM_FULL: "Business Manager",
  CDM_FULL: "Chief Development Manager",
};

const USER_PROFILE = {
  KYC_INFO: "KYC Information",
  CARD_INFO: "Card Information",
  RESET_PASSWORD: "Reset Password",
};

export const CHANGE_PASSWORD = {
  saveBtn: "save",
  title: "Change Password",
  oldPassword: "Old Password",
  newPassword: "New Password",
  confirmPassword: "Confirm Password",
};

export default themeColor;

const footer = {
  COPYRIGHT: "Copyrights © 2020 ",
  CASHBAG: "Cash Bag",
  RIGHTS: ". All Rights Reserved.",
};

export const PAGE_SIZE = 10;

export {
  themeColor,
  themeBgColor,
  footer,
  LOGIN,
  FORGOT_PASSWORD,
  RESET_PASSWORD,
  OTP,
  DASHBOARD,
  USER_PROFILE,
};
